### ISSUE TITLE
prismJS for the Syntax highlighting library

### ISSUE THREAD

**Issue by magnetux** [pytesNET/tail.writer#10]
How to use prismJS for the Syntax highlighting library? is there any documentation to doing this?

**Comment by SamBrishes** [comment]
Hellow,

Sorry, I'm not sure, what you want to ask. 

**prismJS** is a syntax highlighting library, but the support for it depends on the used markup language / on the used markup library. Because tail.writer itself doesn't provide any render function, you need to include [marked](https://github.com/markedjs/marked), [showdown](https://github.com/borgar/textile-js), [textile.js](https://github.com/borgar/textile-js) or [tail.BBSolid](https://github.com/pytesNET/tail.BBSolid) as frontend markup parser.

marked (one of the supported GitHub Flavored Markdown parser) supports prismJS by using the language on the respective code block, such as:
```marked
    ```javascript
    var something = "this is JavaScript";
    ```  
```

I hope I could answer your question, If not, please explain your situation.

Thanks :D 

Sincerely,
Sam.

**Comment by magnetux** [comment]
Thank you, it work now, i'm using bludit 3.8.1, i'm wrong at the first place, because i'm using :

```
<pre class='language-php'>
<code>
	<?php 
	$connection = pg_connect("dbname=postgres");
	$query = "SELECT VERSION()"; 
	$result = pg_query($connection, $query) or die("Cannot execute query: $query\n"); 
	$row = pg_fetch_row($result);
	echo $row[0] . "\n";
	?>
</pre>
</code>
```

i put codes below inside my theme's index.php
```html
<link rel="stylesheet" href="./prism/prism.css"/>
<script src="./prism/prism.js"></script>
```
and using language code after ```
Source : https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting

    ```php
	<?php 
	$connection = pg_connect("dbname=postgres");
	$query = "SELECT VERSION()"; 
	$result = pg_query($connection, $query) or die("Cannot execute query: $query\n"); 
	$row = pg_fetch_row($result);
	echo $row[0] . "\n";
	?>
    ```  

Thank You, Problem solved
