### ISSUE TITLE
Insert content on the fly

### ISSUE THREAD

**Issue by dignajar** [pytesNET/tail.writer#6]
Hi,
I'm trying to create the plugin for Bludit but I need two functions for it.

1) Function for insert content, and if possible in the pointer position, for example I want to insert some image or some text just clicking a button.

2) Function for get the current content, or maybe I can just `document.getElementById("textarea").value`.

Regards
Diego

**Comment by SamBrishes** [comment]
Hellow,

I'm really sorry for the long wait, I didn't notice this issue.

### 1. Add Content
It is possible to insert the content using an own / custom toolbar button, but I guess you want to use the Bludit-own Button(s) outside the editor, right? This is difficult with the current version, because the main write functions are just optimized for the internal system... But I played a bit around, and the following function should work (as shown on this [jsFiddle](https://jsfiddle.net/SamBrishes/1Lm7zbp6/12/))

```javascript
var editor = tail.writer("textarea")[0];

document.getElementById("button").addEventListener("click", function(event){
    event.preventDefault();

    var select = editor.selection(),
        __1 = editor.val.slice(0, select.start),
        __2 = editor.val.slice(select.start, select.end),
        __3 = editor.val.slice(select.end, editor.val.length);
    editor.write(__1 + "++SomeContent++" + __3);
});
```

The function above just splits the content using the "current" pointer position and inserts the custom content to it (a selected text would get replaced). And thanks for the suggestion, I will add a better / simpler way to add content outside the **tail.writer** environment.

### 2. Get Content
You can get the content using the `val` parameter of the main **tail.writer** object or on the usual way of the respective textarea field (as you already mentioned):

```javascript
// Core Object
console.log( document.getElementById("bludit-editor").value );

// tail.writer Object
var editor = tail.writer(document.getElementById("bludit-editor"));
console.log( editor.val );
```

Sincerely,
Sam.

**Comment by dignajar** [comment]
Hi,
yes works perfect, would be good to include this functions to the core.
For example:
```
tail.writer.insertContent("Some content");
```

```
var content = tail.writer.getContent();
```

I created the plugin for Bludit.
https://github.com/bludit-plugins/tail.writer

Feel free to do any change, you have better developer skill with JavaScript.

**Comment by SamBrishes** [comment]
Hellow,

thanks, that's really cool :D 

I will check and maintain the plugin with the next major release (which will also implement a better get / write content interface, of course).

Sincerely,
Sam.
